grammar kismet;
world :
  fact+;

fact :
  location | trait | constraint | actions
  ;

NUMBER : [0-9]+;
TERM : [a-z]+[a-zA-Z0-9_]*;
VAR : [A-Z]+[a-zA-Z0-9_]*;

name : TERM;
count : NUMBER;

location:
  'location' name count ';';

trait:
  name ':' (modifier|goto)* ';';
