default location:.


initialization church:

	select [1] character as deacon:
		is deacon of church,
        is employee at church,
	:where 
		age = [60:80],
		not employee of Location,
		is traditionalist,	
		is believer;
		
	select [1:2] character as priest:
		is priest of church,
        is employee at church,
	:where 
		age = [30:70],
		not employee of Location;	
        
    create [1] location as church:
		location_type = "church",
        has deacon of deacon,
        has priest of priest,
		name = "[The [Temple|Church] of [Starry|Everlasting|Loving|Immortal] [Wisdom|Truth|Revelation]]".
		
initialization boarding_house:
    let FamilyName = "#lastNames#";

    select [1] character as owner:
        is owner of boarding_house,
        is employee at boarding_house,
        is resident at boarding_house,
        last_name = FamilyName,
        is married to housekeeper,
        likes housekeeper = [10],
    :where
        age = [50:70],
        not employee of Location,
        not resident of Location,
        is not married;
        
    select [1] character as housekeeper:
        is housekeeper of boarding_house,
        is employee at boarding_house,
        is resident at boarding_house,
        last_name = FamilyName,
        is married to owner,
        likes owner = [10],
    :where
        age = [50:70],
        not employee of Location,
        not resident of Location,
        not married;
        
    select [1:2] character as boarder:
        is boarder at boarding_house,
        is resident of boarding_house,
    :where
        age = [22:30],
        not resident of Location;
        
    create [1] location as boarding_house:
        location_type = "boarding_house",
        has owner of owner,
        has housekeeper of housekeeper,
        has boarder of boarder,
        name = "[[#FamilyName#]'s [Boarding House|House]|[#FamilyName#] [House|Apartment]]".
        
initialization school:
    select [1] character as headmaster:
        is headmaster at school,
        is employee at school,
    :where
        age = [45:70],
        not employee at Location;
        
    create [4:6] character as student:
        is student at school,
        is employee at school,
        age = [6:16],
        is child;
        
    create [1] location as school:
        location_type = "school",
        has headmaster of headmaster,
        has student of student,
        name = "School of Wayward Souls".

initialization bookstore:
    create [1] location as bookstore:
        location_type = "bookstore".
        
    //character: proprietor x1
    //character: customer 0-2
    //detail: name
    //question: can I have sublocations? like a basement or back room?
        
initialization town_square:
    create [1] location as town_square:
        location_type = "town_square".

        
initialization wharf:
    create [1] location as wharf:
        location_type = "wharf".
        
    //character: dockworker x1-2
    //character: fisherman x1-2
    //character: sailor x1
    //character: loiterer x0-2
        
initialization warehouse:
    create [1] location as warehouse:
        location_type = "warehouse".
        
    //character: dockworker
    //character: worker
    //character: union rep
    //character: butcher
    //character: foreman
    //character: owner

initialization bar:
    create [1] location as bar:
        location_type = "bar".
        
    //character: owner
    //character: server
    //character: patrons

default character: 
	last_name = "#lastNames#",
	first_name = "#firstNames#",
	age = [18:50],
	traits = [1:2] traits.

//residences: mansion, shack, etc. etc.
//train station
//historical society
//"n Street": area to loiter, talk, travel through, etc.
//Cemetary
//Park/Greens
//


//initialization minimial_example:
//    create [1] character:.


initialize:
	create [20] character;
	create [1] church;
	create [1] school;
	create [1] boarding_house;
	create [1] bookstore;
	create [1] town_square;
	create [1] wharf;
	create [1] warehouse;
	create [1] bar.