default location:.

initialization bar:
	let OwnerLastName = ownerChar's last_name,
		OwnerFirstName = ownerChar's first_name;
		
	select [1] character as ownerChar:
		is owner of barA,
        is drunkard,
		
	:where 
		age = [28:70],
		not employee of Location,
		not teetotaler;	
		
	create [1] location as barA:
		location_type = "bar",
		name = "[#OwnerLastName#|#OwnerFirstName#]'s [place|bar|tap|public house]".
		
default character: 
	last_name = "#lastNames#",
	first_name = "#firstNames#",
	age = [18:50],
	traits = [3:5] traits.
	
initialization family:
	let FamilyName = "#lastNames#",
	ParentATraits = [3:5] traits,
	ParentBTraits = [3:5] traits;
	
	select [1] character as parentA:
		age = [20:50],
		last_name = FamilyName,
		traits = ParentATraits,
		is married to parentB,
		is parent to child,
        is old,
        is angry = [2:4],
        likes parentB = [5],
		:where 
        is not parent, 
        is not married;
		
	select [1] character as parentB:
		age = [20:50],
		last_name = FamilyName,
		traits = ParentBTraits,
		is married to parentA,
		is parent to child
		:where is not parent, is not married;
	
	create [1:5] character as child:
		age = [1:15],
		last_name = FamilyName,
		traits = [1:2] traits + [0:2] ParentBTraits + [0:2] ParentATraits,
        is young,
		is child to parentA,
		is child to parentB.
	
initialize:
	create [1] character;
	create [3:5] family;
	create [1] bar.