default location:.

initialization bar:
	let OwnerLastName = "#lastNames#",
		OwnerFirstName = "#firstNames#";
		
	create [1] character as owner:
		age = [28:70],
		first_name = OwnerFirstName,
		last_name = OwnerLastName,
		is owner of barA;
		
	select [1] character as owner:
		first_name = OwnerFirstName,
		last_name = OwnerLastName,
		is owner of barA
		
		where 
		age = [28:70],
		not employee of Location,
		not teetotaler;	
		
	create [1] location as barA:
		type = "bar",
		name = "[#OwnerLastName#|#OwnerFirstName#]'s [place|bar|tap|public house]".
		
default character: 
	last_name = "#lastNames#",
	first_name = "#firstNames#",
	age = [18:50],
	traits = [3:5] traits.
	
initialization family:
	let FamilyName = "#lastNames#",
	ParentATraits = [3:5] traits,
	ParentBTraits = [3:5] traits;
	
	select_create [1] character as parentA:
		age = [20:50],
		last_name = FamilyName,
		traits = ParentATraits,
		is married to parentB,
		is parent to child,
		
		where not parent, not married;
		
	create [1] character as parentB:
		age = [20:50],
		last_name = FamilyName,
		traits = ParentBTraits,
		is married to parentA,
		is parent to child;
	
	create [1:5] character as child:
		age = [1:15],
		last_name = FamilyName,
		traits = [1:2] traits + [0:2] ParentBTraits + [0:2] ParentATraits,
		is child to parentA,
		is child to parentB.
	
initialize:
	create [5] character;
	create [3:5] family;
	create [1] bar.